### ISSUE TITLE
Can you explain more specifically about the **Staleness prevention**

### ISSUE THREAD

**Issue by michalyao** [zachm/tscached#14]
Hi,Zach
I am really insterested in this project, after reading your wonderful design, I got lots of inspiration. But I cant get the case you describe in the **staleness prevention**. 
I knew from Google Group that you made a speech about tscached， would you please send me the slides?
Best regards

**Comment by zachm** [comment]
Hello! Sorry for the long delay on response, I've been traveling recently.

For one thing, DESIGN.md is really a brainstorming doc, it's not necessarily very current and may or may not represent what I ended up building. But the idea I was trying to get across goes something like this, in a bit more detail:

When a KairosDB user issues a query, it's all relevant information. Metric name, tags, _time range_, etc. tscached cares about all of this as well, but it removes the time range from consideration of cardinality. To reiterate, _some_metric_name_ + tags _{'hello':'goodbye'}_ represents a cardinal query, BUT: [one year ago, one month ago] will be regarded as equivalent to [one minute ago, now).

Now, obviously those two time ranges will associate completely different data. tscached has to be aware of, and act intelligently on, these two different queries.

We set a Redis TTL equivalent to our KairosDB TTL. If a query is abandoned in Redis, eventually it will be deleted based on this TTL, which prevents Redis from having more data than the real datastore.

Does that answer your question?

PS: Future work: support custom TTLs per KQuery instead of a systemwide level. This would bring us to parity in this arena with the newest KairosDB ;)

**Comment by michalyao** [comment]
Hello! I'm very grateful for your patience, your answer helps me a lot.I have also downloaded the slices you shared on the Google Group. Really a wonderful presentation!

I've been learning tscached these days, but I have to say I just not so familiar with python, and I'm sorry to ask one more question:
We now use Redis Sentinel, does tscached support? If supports, how to configure?

**Comment by zachm** [comment]
Oh no worries, I totally understand having to deal with a project that's not in your strongest language. That's one reason tscached is written in Python rather than Java like KairosDB ;)

I don't see why tscached wouldn't work with Sentinel, but it's going to require a code change. andymccurdy/redis-py already has support but you'll have to open a PR and write tests to integrate that functionality with tscached. Currently we only support single-master Redis clusters.

That said, you really don't need a large Redis cluster for tscached, at least if your use case is the same as mine. The numbers in my talk suggest 0.5 GB would be plenty... but it'd be a great Learn Python project to add the support! Happy to assist in that.

Check this search for where to start:
https://github.com/zachm/tscached/search?q=StrictRedis&type=Code

**Comment by michalyao** [comment]
Life is short, use python! I will have a try and thanks a lot for your help ;-)
